import type { Place } from './places';
import type { Region } from './regions';
import type { Unlock } from './unlocks';

/**
 * Vorschau-Daten für die Web-Vorschau (AP-D) — generiert aus den Seed-Migrationen
 * `20260610120100_seed_places.sql` und `20260611100100_seed_ladenburg.sql`.
 * Wird ausschließlich genutzt, wenn `isPreview` gilt (nur Web + EXPO_PUBLIC_PREVIEW=1).
 */
export const previewPlaces: Place[] = [
  {
    id: 'zugspitze',
    name: 'Zugspitze',
    region: 'Wettersteingebirge',
    type: 'Höchster Gipfel Deutschlands',
    description:
      'Der höchste Berg Deutschlands an der Grenze zu Österreich, gekrönt vom goldenen Gipfelkreuz. Bei klarer Sicht reicht der Blick über vier Länder und unzählige Alpengipfel.',
    elevation_m: 2962,
    lat: 47.4211,
    lng: 10.9863,
    unlock_radius_m: 250,
    badge_motif: 'peak',
    badge_shape: 'shield',
    badge_tone: 'brass',
    active: true,
    region_id: null,
  },
  {
    id: 'watzmann',
    name: 'Watzmann',
    region: 'Berchtesgadener Alpen',
    type: 'Dritthöchster Berg Deutschlands',
    description:
      'Der sagenumwobene König Watzmann mit seiner berüchtigten Ostwand — der höchsten Felswand der Ostalpen. Sein markantes Doppelgipfel-Profil thront über dem Königssee.',
    elevation_m: 2713,
    lat: 47.555,
    lng: 12.9183,
    unlock_radius_m: 300,
    badge_motif: 'twin',
    badge_shape: 'shield',
    badge_tone: 'brass',
    active: true,
    region_id: null,
  },
  {
    id: 'koenigssee',
    name: 'Königssee',
    region: 'Berchtesgaden',
    type: 'Smaragdgrüner Bergsee',
    description:
      'Ein fjordartiger Alpensee von smaragdgrüner Klarheit, eingerahmt von steilen Wänden. Über dem Wasser leuchten die roten Zwiebeltürme der Wallfahrtskirche St. Bartholomä.',
    elevation_m: 603,
    lat: 47.5479,
    lng: 12.9776,
    unlock_radius_m: 400,
    badge_motif: 'lake',
    badge_shape: 'arch',
    badge_tone: 'brass',
    active: true,
    region_id: null,
  },
  {
    id: 'brocken',
    name: 'Brocken',
    region: 'Harz',
    type: 'Höchster Berg Norddeutschlands',
    description:
      'Der neblige Gipfel der Harzer Hexensagen und der Walpurgisnacht. Eine Schmalspurbahn dampft hinauf, oben drehen sich Wetterstation und Antennen im rauen Wind.',
    elevation_m: 1141,
    lat: 51.7991,
    lng: 10.6156,
    unlock_radius_m: 300,
    badge_motif: 'tower',
    badge_shape: 'oval',
    badge_tone: 'pewter',
    active: true,
    region_id: null,
  },
  {
    id: 'feldberg',
    name: 'Feldberg',
    region: 'Schwarzwald',
    type: 'Höchster Schwarzwaldgipfel',
    description:
      'Die höchste Erhebung des Schwarzwalds — weite, baumfreie Kuppen über dunklen Tannenwäldern. Im Winter das südlichste große Skigebiet Deutschlands.',
    elevation_m: 1493,
    lat: 47.874,
    lng: 8.0046,
    unlock_radius_m: 300,
    badge_motif: 'forest',
    badge_shape: 'oval',
    badge_tone: 'copper',
    active: true,
    region_id: null,
  },
  {
    id: 'koenigsstuhl',
    name: 'Königsstuhl',
    region: 'Rügen · Jasmund',
    type: 'Kreidekliff am Meer',
    description:
      'Die berühmteste Kreidefelsformation der Insel Rügen, hoch über der Ostsee im Nationalpark Jasmund. Schon die Romantiker um Caspar David Friedrich pilgerten zu diesem leuchtend weißen Aussichtspunkt.',
    elevation_m: 118,
    lat: 54.5717,
    lng: 13.6628,
    unlock_radius_m: 200,
    badge_motif: 'cliff',
    badge_shape: 'arch',
    badge_tone: 'silver',
    active: true,
    region_id: null,
  },
  {
    id: 'arber',
    name: 'Gr. Arber',
    region: 'Bayerischer Wald',
    type: 'König des Bayerwaldes',
    description:
      'Der „König des Bayerischen Waldes" mit seinen weißen Radarkuppeln und windzerzausten Latschen. Zu seinen Füßen liegen die stillen Arberseen in alten Karen.',
    elevation_m: 1456,
    lat: 49.1125,
    lng: 13.1347,
    unlock_radius_m: 300,
    badge_motif: 'peak',
    badge_shape: 'shield',
    badge_tone: 'pewter',
    active: true,
    region_id: null,
  },
  {
    id: 'wendelstein',
    name: 'Wendelstein',
    region: 'Mangfallgebirge',
    type: 'Aussichtsberg mit Sternwarte',
    description:
      'Ein freistehender Aussichtsberg über dem Voralpenland mit historischer Zahnradbahn, Sternwarte und der höchstgelegenen Kirche Deutschlands. Noch wartet sein Abzeichen auf dich.',
    elevation_m: 1838,
    lat: 47.7036,
    lng: 12.0139,
    unlock_radius_m: 250,
    badge_motif: 'tower',
    badge_shape: 'shield',
    badge_tone: 'copper',
    active: true,
    region_id: null,
  },
  {
    id: 'ladenburg-marktplatz',
    name: 'Marktplatz',
    region: 'Ladenburg · Kurpfalz',
    type: 'Herz der Altstadt',
    description:
      'Fachwerk drängt sich um den Marienbrunnen — seit Römertagen wird hier gehandelt, gefeiert und erzählt. Wer auf dem Marktplatz steht, steht mitten in zwei Jahrtausenden.',
    elevation_m: 98,
    lat: 49.4711,
    lng: 8.6075,
    unlock_radius_m: 150,
    badge_motif: 'tower',
    badge_shape: 'arch',
    badge_tone: 'brass',
    active: true,
    region_id: 'ladenburg',
  },
  {
    id: 'ladenburg-lobdengau-museum',
    name: 'Lobdengau-Museum',
    region: 'Ladenburg · Kurpfalz',
    type: 'Museum im Bischofshof',
    description:
      'Im alten Bischofshof erzählt das Lobdengau-Museum von Lopodunum — dem römischen Ladenburg. Steinerne Götter, Scherben und Inschriften, Schicht um Schicht Geschichte.',
    elevation_m: 99,
    lat: 49.4719,
    lng: 8.6057,
    unlock_radius_m: 150,
    badge_motif: 'tower',
    badge_shape: 'oval',
    badge_tone: 'pewter',
    active: true,
    region_id: 'ladenburg',
  },
  {
    id: 'ladenburg-automuseum',
    name: 'Automuseum Dr. Carl Benz',
    region: 'Ladenburg · Kurpfalz',
    type: 'Museum in der alten Benz-Fabrik',
    description:
      'In der ehemaligen Fabrikhalle von Carl Benz glänzen die Pioniere des Automobils. Hier, wo der Erfinder zuletzt baute, riecht es noch nach Aufbruch und Benzin.',
    elevation_m: 97,
    lat: 49.4665,
    lng: 8.6094,
    unlock_radius_m: 200,
    badge_motif: 'tower',
    badge_shape: 'shield',
    badge_tone: 'copper',
    active: true,
    region_id: 'ladenburg',
  },
  {
    id: 'ladenburg-benzpark',
    name: 'Carl-Benz-Haus & Benzpark',
    region: 'Ladenburg · Kurpfalz',
    type: 'Wohnhaus des Erfinders am Park',
    description:
      'Die Villa des Automobilpioniers mit ihrem Park am Neckar — Alterssitz von Carl und Bertha Benz. Unter alten Bäumen lässt sich erahnen, wohin die erste Ausfahrt führte.',
    elevation_m: 96,
    lat: 49.473,
    lng: 8.6128,
    unlock_radius_m: 200,
    badge_motif: 'forest',
    badge_shape: 'arch',
    badge_tone: 'copper',
    active: true,
    region_id: 'ladenburg',
  },
  {
    id: 'ladenburg-neckarwiese',
    name: 'Neckarwiese',
    region: 'Ladenburg · Kurpfalz',
    type: 'Flussufer vor der Altstadtkulisse',
    description:
      'Weite Wiesen am Neckarufer, dahinter die Türme der Altstadt. Hier wird gepicknickt, gestaunt und in den Sonnenuntergang geschaut — Ladenburgs grünes Wohnzimmer.',
    elevation_m: 95,
    lat: 49.4748,
    lng: 8.6066,
    unlock_radius_m: 200,
    badge_motif: 'lake',
    badge_shape: 'arch',
    badge_tone: 'silver',
    active: true,
    region_id: 'ladenburg',
  },
  {
    id: 'ladenburg-martinstor',
    name: 'Martinstor',
    region: 'Ladenburg · Kurpfalz',
    type: 'Stadttor der mittelalterlichen Mauer',
    description:
      'Das letzte erhaltene Stadttor Ladenburgs, eingebettet in den Rest der alten Mauer. Wer hindurchgeht, betritt die Stadt wie die Reisenden vor sechshundert Jahren.',
    elevation_m: 98,
    lat: 49.4694,
    lng: 8.6062,
    unlock_radius_m: 150,
    badge_motif: 'tower',
    badge_shape: 'shield',
    badge_tone: 'pewter',
    active: true,
    region_id: 'ladenburg',
  },
  {
    id: 'ladenburg-galluskirche',
    name: 'Galluskirche',
    region: 'Ladenburg · Kurpfalz',
    type: 'Gotische Kirche über römischen Mauern',
    description:
      'Die evangelische Galluskirche steht auf den Fundamenten einer römischen Basilika — Glaube über Forum. Ihr Turm gehört zur Silhouette Ladenburgs wie der Neckar zur Stadt.',
    elevation_m: 100,
    lat: 49.4706,
    lng: 8.6051,
    unlock_radius_m: 150,
    badge_motif: 'tower',
    badge_shape: 'oval',
    badge_tone: 'brass',
    active: true,
    region_id: 'ladenburg',
  },
];

export const previewRegions: Region[] = [
  { id: 'baden-wuerttemberg', name: 'Baden-Württemberg', parent_id: null, active: true },
  { id: 'ladenburg', name: 'Ladenburg', parent_id: 'baden-wuerttemberg', active: true },
];

/** Einige Orte gelten in der Vorschau als erwandert, damit beide Zustände sichtbar sind. */
export const previewUnlocks: Unlock[] = [
  { place_id: 'zugspitze', unlocked_at: '2026-08-14T09:42:00Z' },
  { place_id: 'koenigssee', unlocked_at: '2026-08-16T15:10:00Z' },
  { place_id: 'brocken', unlocked_at: '2026-09-03T11:25:00Z' },
  { place_id: 'ladenburg-marktplatz', unlocked_at: '2026-09-20T17:05:00Z' },
  { place_id: 'ladenburg-martinstor', unlocked_at: '2026-09-20T17:31:00Z' },
  { place_id: 'ladenburg-galluskirche', unlocked_at: '2026-09-21T10:12:00Z' },
];
